# Generated by Django 2.0.7 on 2018-07-27 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board_number', models.CharField(max_length=16, verbose_name='Бортовой номер')),
                ('current_weight', models.IntegerField(default=0, verbose_name='Текущий вес')),
            ],
        ),
        migrations.CreateModel(
            name='TruckModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Модель грузовика')),
                ('carrying', models.IntegerField(verbose_name='Максимальная грузоподьемность')),
            ],
        ),
        migrations.AddField(
            model_name='truck',
            name='truck_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='truck', to='trucks_load.TruckModel', verbose_name='Модель грузовика'),
        ),
    ]
